### PR TITLE
Replace naming tests

### PR DESCRIPTION
**Pull request by zhelezniak88**
Hello. 
I replaced naming all Kata tests with TestKata#** and all Solution tests with TestSolution#**. I hope that you'll approve my fixs.

### CODE REVIEW

**Review by c-guntur — CHANGES_REQUESTED** [review]
Code changes are perfect. Please also update the README.md in each module as a part of this.

**Comment by zhelezniak88** [comment]
In this case, can I make changes in java-optional README.md ( Java Time API to Java Optional API, from another issue)?

**Comment by zhelezniak88** [comment]
Updated all README.md in each modules.

**Comment by c-guntur** [comment]
Closes #9

**Comment by c-guntur** [comment]
Closes #12

**Comment by zhelezniak88** [comment]
Thank you for this experience.

**Comment by c-guntur** [comment]
@zhe1ezniak - Thank you for your contribution ! Please stay active on the repo !

**Pull request merged**
